#pragma once

extern "C" DRIVER_INITIALIZE DriverEntry;
extern "C" NTSTATUS DriverEntry(_In_ PDRIVER_OBJECT DriverObject, _In_ PUNICODE_STRING RegistryPath);

EVT_WDF_DRIVER_DEVICE_ADD YomagEvtDeviceAdd;
EVT_WDF_DEVICE_PREPARE_HARDWARE YomagEvtDevicePrepareHardware;
EVT_WDF_DEVICE_RELEASE_HARDWARE YomagEvtDeviceReleaseHardware;
EVT_WDF_OBJECT_CONTEXT_CLEANUP YomagEvtDeviceContextCleanup;
